### ISSUE TITLE
ReferenceField not working

### ISSUE THREAD

**Issue by k2glyph** [kimkha/aor-loopback#9]
This is my code 
```
<ReferenceField label={'Album'} source="albumId" reference="albums" allowEmpty linkType={false}>
        <TextField source="name" />
</ReferenceField>
```
This  is the error
```
11:36:46.115 Navigated to http://localhost:3000/
11:36:48.902 proxyConsole.js:54 uncaught at handleFetch TypeError: Cannot read property 'data' of undefined
    at Function.mapStateToProps [as mapToProps] (http://localhost:3000/static/js/bundle.js:6873:64)
    at mapToPropsProxy (http://localhost:3000/static/js/bundle.js:128653:46)
    at Function.detectFactoryAndVerify (http://localhost:3000/static/js/bundle.js:128662:19)
    at mapToPropsProxy (http://localhost:3000/static/js/bundle.js:128653:46)
    at handleFirstCall (http://localhost:3000/static/js/bundle.js:128487:18)
    at pureFinalPropsSelector (http://localhost:3000/static/js/bundle.js:128535:81)
    at Object.runComponentSelector [as run] (http://localhost:3000/static/js/bundle.js:127933:25)
    at Connect.initSelector (http://localhost:3000/static/js/bundle.js:128085:23)
    at new Connect (http://localhost:3000/static/js/bundle.js:128026:15)
    at http://localhost:3000/static/js/bundle.js:108118:18
    at measureLifeCyclePerf (http://localhost:3000/static/js/bundle.js:107899:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://localhost:3000/static/js/bundle.js:108117:16)
    at ReactCompositeComponentWrapper._constructComponent (http://localhost:3000/static/js/bundle.js:108108:19)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3000/static/js/bundle.js:108011:21)
    at Object.mountComponent (http://localhost:3000/static/js/bundle.js:114771:35)
    at ReactDOMComponent.mountChildren (http://localhost:3000/static/js/bundle.js:114109:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3000/static/js/bundle.js:109556:32)
    at ReactDOMComponent.mountComponent (http://localhost:3000/static/js/bundle.js:109375:12)
    at Object.mountComponent (http://localhost:3000/static/js/bundle.js:114771:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3000/static/js/bundle.js:108194:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3000/static/js/bundle.js:108081:21)
    at Object.mountComponent (http://localhost:3000/static/js/bundle.js:114771:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3000/static/js/bundle.js:108194:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3000/static/js/bundle.js:108081:21)
    at Object.mountComponent (http://localhost:3000/static/js/bundle.js:114771:35)
    at ReactDOMComponent.mountChildren (http://localhost:3000/static/js/bundle.js:114109:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3000/static/js/bundle.js:109556:32)
    at ReactDOMComponent.mountComponent (http://localhost:3000/static/js/bundle.js:109375:12)
    at Object.mountComponent (http://localhost:3000/static/js/bundle.js:114771:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3000/static/js/bundle.js:108194:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3000/static/js/bundle.js:108081:21)
    at Object.mountComponent (http://localhost:3000/static/js/bundle.js:114771:35)
    at Object.updateChildren (http://localhost:3000/static/js/bundle.js:107692:51)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3000/static/js/bundle.js:114079:32)
    at ReactDOMComponent._updateChildren (http://localhost:3000/static/js/bundle.js:114183:31)
    at ReactDOMComponent.updateChildren (http://localhost:3000/static/js/bundle.js:114170:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3000/static/js/bundle.js:109799:12)
    at ReactDOMComponent.updateComponent (http://localhost:3000/static/js/bundle.js:109613:10)
    at ReactDOMComponent.receiveComponent (http://localhost:3000/static/js/bundle.js:109575:10)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:114850:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:108577:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3000/static/js/bundle.js:108547:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/static/js/bundle.js:108468:12)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:3000/static/js/bundle.js:108370:10)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:114850:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:108577:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3000/static/js/bundle.js:108547:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/static/js/bundle.js:108468:12)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:3000/static/js/bundle.js:108370:10)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:114850:22)
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:54
log @ utils.js:225
(anonymous) @ proc.js:483
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:476
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
```

**Comment by k2glyph** [comment]
I just fixed it now.

**Comment by kimkha** [comment]
Could you please share your App.js? I think you have a piece of missing code config...

**Comment by kimkha** [comment]
Thank. If you can, please share how to fix your issue.
